CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY, username VARCHAR(100) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, nickname VARCHAR(100), friends_json TEXT, groups_json TEXT, registered_at BIGINT NOT NULL DEFAULT 0, last_login_at BIGINT NOT NULL DEFAULT 0, rank_points INT NOT NULL DEFAULT 0, wins INT NOT NULL DEFAULT 0, losses INT NOT NULL DEFAULT 0, draws INT NOT NULL DEFAULT 0, current_streak INT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE');
CREATE INDEX IF NOT EXISTS idx_users_rank_points ON users(rank_points);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
CREATE TABLE IF NOT EXISTS matches (id BIGINT PRIMARY KEY, game_type VARCHAR(40) NOT NULL, player_a_id BIGINT, player_b_id BIGINT, winner_id BIGINT, result VARCHAR(20), rank_delta_a INT NOT NULL DEFAULT 0, rank_delta_b INT NOT NULL DEFAULT 0, board_log TEXT, created_at BIGINT NOT NULL DEFAULT 0, finished_at BIGINT NOT NULL DEFAULT 0, CONSTRAINT fk_match_player_a FOREIGN KEY (player_a_id) REFERENCES users(id), CONSTRAINT fk_match_player_b FOREIGN KEY (player_b_id) REFERENCES users(id), CONSTRAINT fk_match_winner FOREIGN KEY (winner_id) REFERENCES users(id));
CREATE INDEX IF NOT EXISTS idx_matches_finished_at ON matches(finished_at);
CREATE INDEX IF NOT EXISTS idx_matches_player_a ON matches(player_a_id);
CREATE INDEX IF NOT EXISTS idx_matches_player_b ON matches(player_b_id);
CREATE TABLE IF NOT EXISTS admin_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, action VARCHAR(80) NOT NULL, target VARCHAR(120), detail_text TEXT, created_at BIGINT NOT NULL);
